FROM gocd/gocd-agent:15.1.0

# Added docker to gocd-agent image as combination of current docker install docs + https://github.com/jpetazzo/dind/blob/master/Dockerfile

# install wget
RUN echo "deb https://dl.bintray.com/sbt/debian /" > /etc/apt/sources.list.d/sbt.list && \
    apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 642AC823 && \
    apt-get update &&\
    apt-get -y install apt-transport-https &&\
    apt-get -y install wget && \
    apt-get -y install maven && \
    apt-get -y install openjdk-8-jre-headless && \
    apt-get -y install sbt && \
    apt-get -y install scala

#install docker
RUN wget -qO- https://get.docker.com/ | sh

# Define additional metadata
VOLUME /var/lib/docker

# preparing image for docker service
RUN mkdir -p /etc/my_init.d
ADD gocd-agent/init-docker.sh /etc/my_init.d/init-docker.sh

# start docker service
RUN mkdir /etc/service/docker
ADD gocd-agent/docker.sh /etc/service/docker/run

# allow go user to use docker
RUN usermod -aG docker go

# add self signed cert for private registry usage
ADD gocd-agent/registry.crt /etc/docker/certs.d/192.168.59.103:5000/ca.crt


RUN apt-get -y install unzip curl python && \
  curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip" && \
  unzip awscli-bundle.zip && \
  ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws

RUN apt-get -y install apt-transport-https ca-certificates && \
  #echo "deb https://apt.dockerproject.org/repo ubuntu-xenial main" > /etc/apt/sources.list.d/docker.list && \
  #apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D && \
  #apt-get update && \
  #apt-get -y install docker.io && \
  curl -L https://github.com/docker/compose/releases/download/1.8.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose && \
  chmod +x /usr/local/bin/docker-compose

RUN apt-get -y install curl && \
  curl -sL https://deb.nodesource.com/setup_6.x | bash && \
  apt-get -y install nodejs build-essential